### ISSUE TITLE
build fails with GCC 6.0

### ISSUE THREAD

**Issue by morxa** [rdiankov/collada-dom#22]
Due to stricter type checking, collada-dom fails to build with GCC 6.0:

    /builddir/build/BUILD/collada-dom-2.4.4/dom/src/dae/daeMetaGroup.cpp:29:10: error: cannot convert 'bool' to 'daeElement*' in return
       return false;
              ^~~~~

It looks like the new GCC release does not allow implicit type conversions of this kind anymore.

The bug was found during a Fedora mass rebuild for Fedora 24. See [RedHat Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1307391) and the [Full build log](https://bugzilla.redhat.com/attachment.cgi?id=1124243) for details.

**Comment by rdiankov** [comment]
thanks!
pushed here 8e65676c1cbecde1c0c4d8c2e1cfb20fc49c410b

**Comment by morxa** [comment]
Thanks for fixing this!
