### ISSUE TITLE
Build failure with Boost 1.85.0

### ISSUE THREAD

**Issue by cho-m** [rdiankov/collada-dom#42]
Build with Boost 1.85.0 fails and outputs errors like:
```
In file included from /tmp/collada-dom-20240425-5735-4akd4c/collada-dom-2.5.0/dom/src/1.5/dom/domAnimation.cpp:1:
/tmp/collada-dom-20240425-5735-4akd4c/collada-dom-2.5.0/dom/include/dae.h:28:10: fatal error: 'boost/filesystem/convenience.hpp' file not found
#include <boost/filesystem/convenience.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This is due to removal of `convenience.hpp` (https://www.boost.org/doc/libs/1_85_0/libs/filesystem/doc/deprecated.html). The includes need to be updated depending on what functions/etc are needed.

EDIT: Also need to update some removed APIs, e.g.
```
/tmp/collada-dom-20240425-12463-zjold7/collada-dom-2.5.0/dom/src/dae/daeZAEUncompressHandler.cpp:274:35: error: no member named 'branch_path' in 'boost::filesystem::path'
    std::string dir = archivePath.branch_path().string();
                      ~~~~~~~~~~~ ^
1 error generated.
```

---

Seen while updating Boost in Homebrew - https://github.com/Homebrew/homebrew-core/pull/169237

**Comment by magicaldave** [comment]
Hi, this is breaking builds of openmw on arch and requiring workarounds for users. Is there any possibility to get an update on this?

**Comment by traversaro** [comment]
A patch is available at https://github.com/rdiankov/collada-dom/pull/43 . Not sure if the upstream is actually active at this point.

**Comment by Zennwah** [comment]
> Hi, this is breaking builds of openmw on arch and requiring workarounds for users. Is there any possibility to get an update on this?

Just downgrade boost and boost-libs to 1.83 and add to ignorepkg. OpenMW from AUR builds normally now that collada builds without errors, no other workaround is needed.

**Comment by CBJamo** [comment]
collada-dom now builds on arch with boost 1.85, no need to downgrade.
